name: Sync Markdown Posts

on:
  push:
    paths:
      - '2024/4월/*.md'

jobs:
  sync_posts:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout myTil repository
      uses: actions/checkout@v2
      with:
        repository: 'rosmontisu/TIL'
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install PyGithub

    - name: Rename and move the Markdown file
      run: python rename_and_move.py

    - name: Commit files to myProject.github.io
      uses: EndBug/add-and-commit@v7
      with:
        author_name: hepari
        author_email: rosmontisu@gmail.com
        message: 'Automated commit from myTil to blog'
        repository: 'rosmontisu/rosmontisu.github.io'
        token: ${{ secrets.GITHUB_TOKEN }}
        add: '_posts/*'
