name: Sync Markdown Posts

on:
  push:
    branches:
      - main
    paths:
      - 'TIL/**'

jobs:
  sync_posts:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout myTil repository
      uses: actions/checkout@v2
      with:
        repository: 'rosmontisu/TIL'
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install PyGithub

    - name: Rename and move the Markdown file
      run: python scripts/rename_and_move.py

    - name: Checkout myProject.github.io repository
      uses: actions/checkout@v2
      with:
        repository: 'rosmontisu/rosmontisu.github.io'
        token: ${{ secrets.GITHUB_TOKEN }}
        path: 'blog'

    - name: Commit files to myProject.github.io
      run: |
        cd blog
        git config --local user.email "rosmontisu@gmail.com"
        git config --local user.name "hepari"
        git add _posts/*
        git commit -m 'Automated commit from myTil to blog'
        git push
